# Generated by Django 4.2.7 on 2023-12-25 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='stress_address',
            new_name='street_address',
        ),
    ]
